language: perl
install:
  - cpanm -n AnyEvent Test::CPAN::Changes Test::EOL Test::NoTabs Test::Pod::Spelling::CommonMistakes
  - cpanm -n App::cpanminus
  - cpanm -n https://github.com/stevan/p5-mop-redux.git
  - cpanm -n https://github.com/rafl/twigils.git
script: HARNESS_IS_VERBOSE=1 prove -lvr t xt
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
